kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment
spec:
  # 1. How many copies of each pod do we want?
  replicas: 1

  # 3. Which pods are managed by this deployment?
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      deploy: kubeserver
  
  # This template field is a regular pod configuration 
  # nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        deploy: kubeserver
    spec:
      containers:
      - name: ftserver
        image: ftserver:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
